name: Generate SVG and deploy

on:
  schedule:
    - cron: "0 0 * * 0" # 毎週日曜0:00 UTC（日本時間で日曜9:00）
  workflow_dispatch: # 手動実行も可
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt || true  # 必要なら

      - name: Run script
        run: python svgfy.py
        env:
          GITHUB_TOKEN: ${{ secrets.secrets }}

      - name: Deploy SVG to branch
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: gh-pages
          force_orphan: true
